// Nelayan Trip Agent — interactive demo runtime.
//
// Two modes:
//   scripted  — deterministic, no API key, pre-baked tool trace + bubbles.
//   live      — bring your own OpenAI-compatible endpoint. Tool trace stays
//               deterministic (those represent real tool calls); the agent's
//               natural-language replies are generated by your LLM.
//
// Provider settings persist to localStorage (key only ever lives in the tab).

(function () {
  "use strict";

  // ---------- DOM refs ----------

  var screen = document.getElementById("phone-screen");

  var provMode = document.getElementById("prov-mode");
  var provPreset = document.getElementById("prov-preset");
  var provBase = document.getElementById("prov-base");
  var provModel = document.getElementById("prov-model");
  var provKey = document.getElementById("prov-key");
  var provModePill = document.getElementById("prov-mode-pill");

  // ---------- presets ----------

  var PRESETS = {
    mimo: {
      base: "https://api.mimo.xiaomi.com/v1",
      model: "mimo-orbit-pro",
      note: "Xiaomi MiMo (OpenAI-compatible)"
    },
    openai: {
      base: "https://api.openai.com/v1",
      model: "gpt-4o-mini",
      note: "OpenAI"
    },
    groq: {
      base: "https://api.groq.com/openai/v1",
      model: "llama-3.1-70b-versatile",
      note: "Groq Cloud"
    },
    xai: {
      base: "https://api.x.ai/v1",
      model: "grok-2-mini",
      note: "xAI"
    },
    together: {
      base: "https://api.together.xyz/v1",
      model: "meta-llama/Llama-3.1-70B-Instruct-Turbo",
      note: "Together AI"
    },
    custom: {
      base: "",
      model: "",
      note: "Custom endpoint"
    }
  };

  var STORAGE_KEY = "ntra.provider.v1";

  function loadProv() {
    try {
      var raw = localStorage.getItem(STORAGE_KEY);
      if (!raw) return null;
      return JSON.parse(raw);
    } catch (e) {
      return null;
    }
  }

  function saveProv() {
    var s = {
      mode: provMode.value,
      preset: provPreset.value,
      base: provBase.value.trim(),
      model: provModel.value.trim(),
      key: provKey.value
    };
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(s));
    } catch (e) {
      /* private mode etc */
    }
  }

  function applyPreset(name) {
    var p = PRESETS[name];
    if (!p) return;
    if (name !== "custom") {
      provBase.value = p.base;
      provModel.value = p.model;
    }
  }

  function refreshModePill() {
    var live = provMode.value === "live";
    provModePill.textContent = live ? "LIVE" : "SCRIPTED";
    provModePill.classList.toggle("live", live);
  }

  function initProvider() {
    var saved = loadProv();
    if (saved) {
      provMode.value = saved.mode || "scripted";
      provPreset.value = saved.preset || "mimo";
      provBase.value = saved.base || PRESETS[provPreset.value].base;
      provModel.value = saved.model || PRESETS[provPreset.value].model;
      provKey.value = saved.key || "";
    } else {
      applyPreset("mimo");
    }
    refreshModePill();

    [provMode, provPreset, provBase, provModel, provKey].forEach(function (el) {
      el.addEventListener("change", function () {
        saveProv();
        refreshModePill();
      });
      el.addEventListener("input", saveProv);
    });
    provPreset.addEventListener("change", function () {
      applyPreset(provPreset.value);
      saveProv();
    });
  }

  function isLive() {
    return provMode.value === "live" && provKey.value.trim() && provBase.value.trim() && provModel.value.trim();
  }

  // ---------- helpers ----------

  function clearScreen() {
    screen.innerHTML = "";
  }

  function pickLang() {
    var lang = document.documentElement.getAttribute("lang") || "en";
    if (lang === "zh-CN") lang = "cn";
    return lang;
  }

  function pickLangText(map) {
    return map[pickLang()] || map.en;
  }

  function bubble(kind, text) {
    var el = document.createElement("div");
    el.className = "bubble bubble-" + kind;
    el.textContent = text;
    screen.appendChild(el);
    screen.scrollTop = screen.scrollHeight;
    return el;
  }

  function bubbleMap(kind, textMap) {
    return bubble(kind, pickLangText(textMap));
  }

  function trace(boxId, lines) {
    var box = document.getElementById(boxId);
    box.innerHTML = "";
    lines.forEach(function (l) {
      var div = document.createElement("div");
      div.className = "trace-line";
      var tier = document.createElement("span");
      tier.className = "tier" + (l.tier === "smart" ? " smart" : "");
      tier.textContent = "[" + l.tier + "]";
      div.appendChild(tier);
      div.appendChild(document.createTextNode(" " + l.msg));
      box.appendChild(div);
    });
  }

  function step(delay, fn) {
    return new Promise(function (resolve) {
      setTimeout(function () {
        fn();
        resolve();
      }, delay);
    });
  }

  // ---------- live LLM call ----------

  var LANG_NAMES = { en: "English", id: "Bahasa Indonesia", cn: "简体中文" };

  function buildSystemPrompt() {
    var lang = pickLang();
    return [
      "You are the Nelayan Trip Agent — an autonomous assistant for Pak Yusuf,",
      "a 45-year-old traditional small-boat fisher in Pangkep, South Sulawesi,",
      "Indonesia. He runs a 7 GT wooden boat with 2 crew on 2-4 day trips.",
      "",
      "You are speaking directly to Pak Yusuf. Reply in " + LANG_NAMES[lang] + ".",
      "Use short, plain sentences a working fisher can read on a phone. Stay",
      "warm but practical. No marketing fluff. Use Indonesian fish, port, and",
      "place names verbatim (tongkol, cakalang, kembung, Pangkep, Spermonde,",
      "TPI). Respect his time — concise wins.",
      "",
      "You receive a structured situation block. Respond with 1-3 short",
      "messages, separated by a blank line. Do not invent data points the",
      "situation block does not give you."
    ].join("\n");
  }

  async function callLLM(situation, traceBoxId) {
    var url = provBase.value.trim().replace(/\/$/, "") + "/chat/completions";
    var body = {
      model: provModel.value.trim(),
      messages: [
        { role: "system", content: buildSystemPrompt() },
        { role: "user", content: situation }
      ],
      temperature: 0.4,
      max_tokens: 360
    };

    var traceBox = document.getElementById(traceBoxId);
    var liveLine = document.createElement("div");
    liveLine.className = "trace-line";
    liveLine.innerHTML =
      '<span class="tier smart">[live]</span> POST ' +
      url +
      " · model=" +
      provModel.value.trim();
    traceBox.appendChild(liveLine);

    var t0 = performance.now();
    var resp;
    try {
      resp = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: "Bearer " + provKey.value.trim()
        },
        body: JSON.stringify(body)
      });
    } catch (e) {
      throw new Error("network/CORS: " + e.message);
    }
    var elapsed = Math.round(performance.now() - t0);

    if (!resp.ok) {
      var errBody = await resp.text();
      throw new Error("HTTP " + resp.status + " · " + errBody.slice(0, 200));
    }
    var json = await resp.json();
    var content = (json.choices && json.choices[0] && json.choices[0].message && json.choices[0].message.content) || "";

    var doneLine = document.createElement("div");
    doneLine.className = "trace-line";
    doneLine.innerHTML =
      '<span class="tier smart">[live]</span> ← ' +
      resp.status +
      " · " +
      elapsed +
      "ms · " +
      (json.usage ? json.usage.total_tokens + " tok" : "ok");
    traceBox.appendChild(doneLine);

    return content.trim();
  }

  function renderLLMReply(text) {
    var parts = text.split(/\n\s*\n/).map(function (p) {
      return p.trim();
    }).filter(Boolean);
    if (parts.length === 0) parts = [text];
    var p = Promise.resolve();
    parts.forEach(function (part, i) {
      p = p.then(function () {
        return step(i === 0 ? 100 : 700, function () {
          bubble("agent", part);
        });
      });
    });
    return p;
  }

  // ---------- tabs ----------

  var tabBtns = document.querySelectorAll(".tab-btn");
  var panes = document.querySelectorAll(".tab-pane");
  tabBtns.forEach(function (b) {
    b.addEventListener("click", function () {
      tabBtns.forEach(function (x) {
        x.classList.remove("active");
      });
      panes.forEach(function (p) {
        p.classList.remove("active");
      });
      b.classList.add("active");
      var t = b.getAttribute("data-tab");
      document.querySelector('[data-pane="' + t + '"]').classList.add("active");
    });
  });

  // ---------- pre-trip scenario ----------

  function pretripContext() {
    var species = document.getElementById("pre-species").value;
    var len = parseInt(document.getElementById("pre-len").value, 10);
    var fuel = parseInt(document.getElementById("pre-fuel").value, 10);
    var fuelEst = Math.round(50 * len * 1.05);
    var spotMap = {
      tongkol: { name: "Spermonde shelf, 12 nm SW", bearing: "215°", note: "Strong upwelling forecast." },
      kembung: { name: "Pulau Kapoposang outer reef", bearing: "270°", note: "New moon, plankton bloom likely." },
      cakalang: { name: "Selat Makassar drop-off, 18 nm W", bearing: "260°", note: "Cross-current at 1.2 kn — favourable." }
    };
    var spot = spotMap[species];
    return { species: species, len: len, fuel: fuel, fuelEst: fuelEst, spot: spot, fuelOk: fuel >= fuelEst };
  }

  function pretripTraceLines(ctx) {
    return [
      { tier: "cheap", msg: "tool: bmkg.fetchForecast(lat=-4.8, lon=119.5, hours=72)" },
      { tier: "cheap", msg: "tool: copernicus.getCurrents(area='spermonde', hours=72)" },
      { tier: "cheap", msg: "tool: catchHistory.recall(species='" + ctx.species + "', last=10)" },
      { tier: "cheap", msg: "tool: fuelCalc(distanceNm=" + (ctx.len * 24) + ", boat='7gt-wood') = " + ctx.fuelEst + " L" },
      { tier: "smart", msg: "reason: cross-ref forecast vs catch-log → recommend bearing " + ctx.spot.bearing }
    ];
  }

  function pretripScripted(ctx) {
    var spot = ctx.spot;
    return [
      {
        delay: 100,
        text: {
          en: "Good morning, Pak Yusuf. Pulling weather and currents for the " + ctx.len + "-day trip.",
          id: "Selamat pagi Pak Yusuf. Saya cek cuaca dan arus untuk trip " + ctx.len + " hari.",
          cn: "Pak Yusuf 早上好。我正在查询 " + ctx.len + " 天行程的天气和洋流。"
        }
      },
      {
        delay: 600,
        kind: "tool",
        text: {
          en: "→ BMKG: 8–12 kn winds from SE, swell 0.6–1.1 m. Safe.",
          id: "→ BMKG: angin 8–12 kn dari tenggara, gelombang 0.6–1.1 m. Aman.",
          cn: "→ BMKG：东南风 8–12 节，浪高 0.6–1.1 m。安全。"
        }
      },
      {
        delay: 700,
        kind: "tool",
        text: {
          en: "→ Surface current: 0.4–0.8 kn westward. Helps a fuel-efficient return.",
          id: "→ Arus permukaan: 0.4–0.8 kn ke barat. Cocok untuk pulang berhemat solar.",
          cn: "→ 表面洋流：0.4–0.8 节向西。利于返航省油。"
        }
      },
      {
        delay: 800,
        text: {
          en:
            "My plan:\n• Depart 04:30 (slack tide)\n• Spot: " +
            spot.name +
            "\n• Bearing " +
            spot.bearing +
            "\n• Fuel needed ~" +
            ctx.fuelEst +
            " L (on board: " +
            ctx.fuel +
            " L) " +
            (ctx.fuelOk ? "✓ enough" : "⚠ short by " + (ctx.fuelEst - ctx.fuel) + " L"),
          id:
            "Rencana saya:\n• Berangkat 04:30 (slack tide)\n• Tujuan: " +
            spot.name +
            "\n• Bearing " +
            spot.bearing +
            "\n• Solar perlu ~" +
            ctx.fuelEst +
            " L (di tangki: " +
            ctx.fuel +
            " L) " +
            (ctx.fuelOk ? "✓ cukup" : "⚠ kurang " + (ctx.fuelEst - ctx.fuel) + " L"),
          cn:
            "我的计划：\n• 04:30 出发（平潮）\n• 目的地：" +
            spot.name +
            "\n• 航向 " +
            spot.bearing +
            "\n• 需油约 " +
            ctx.fuelEst +
            " 升（船上：" +
            ctx.fuel +
            " 升）" +
            (ctx.fuelOk ? "✓ 足够" : "⚠ 缺 " + (ctx.fuelEst - ctx.fuel) + " 升")
        }
      },
      {
        delay: 800,
        text: {
          en: ctx.fuelOk ? "Send the ETA to your wife via SMS?" : "I'd suggest topping up at SPBN first. OK?",
          id: ctx.fuelOk ? "Mau saya kirim ETA ke istri Pak via SMS?" : "Saya saran mampir SPBN dulu sebelum berangkat. OK?",
          cn: ctx.fuelOk ? "需要我用短信把预计到达时间发给您夫人吗？" : "建议先去 SPBN 加油。可以吗？"
        }
      }
    ];
  }

  function pretripSituationText(ctx) {
    return [
      "Phase: pre-trip planning.",
      "Trip length: " + ctx.len + " days.",
      "Target species: " + ctx.species + ".",
      "Fuel on board: " + ctx.fuel + " L.",
      "Fuel needed (computed): ~" + ctx.fuelEst + " L.",
      "BMKG forecast: 8-12 kn SE wind, swell 0.6-1.1 m, safe.",
      "Surface current: 0.4-0.8 kn westward, helps fuel-efficient return.",
      "Recommended spot: " + ctx.spot.name + ", bearing " + ctx.spot.bearing + ".",
      "Catch-log signal: " + ctx.spot.note,
      "Fuel sufficient: " + (ctx.fuelOk ? "yes" : "NO, short " + (ctx.fuelEst - ctx.fuel) + " L"),
      "",
      "Greet Pak Yusuf, summarise the conditions, lay out the plan, then ask",
      "if he wants the ETA SMS sent" + (ctx.fuelOk ? "" : " (note: he must refuel at SPBN first)") + "."
    ].join("\n");
  }

  async function runPretrip() {
    clearScreen();
    var btn = document.getElementById("run-pre");
    btn.disabled = true;
    var ctx = pretripContext();
    trace("trace-pre", pretripTraceLines(ctx));

    try {
      if (isLive()) {
        var reply = await callLLM(pretripSituationText(ctx), "trace-pre");
        await renderLLMReply(reply);
      } else {
        var script = pretripScripted(ctx);
        var p = Promise.resolve();
        script.forEach(function (s) {
          p = p.then(function () {
            return step(s.delay, function () {
              bubbleMap(s.kind || "agent", s.text);
            });
          });
        });
        await p;
      }
    } catch (e) {
      bubble("agent", "⚠ live API error: " + e.message);
    } finally {
      btn.disabled = false;
    }
  }

  // ---------- at-sea scenario ----------

  var SEA_EVENTS = {
    heartbeat: {
      traceLines: [
        { tier: "cheap", msg: "trigger: cron(every=4h)" },
        { tier: "cheap", msg: "tool: gps.read() = -4.92, 119.21" },
        { tier: "cheap", msg: "tool: sms.send(to='+62812..wife', body=...)" }
      ],
      situation:
        "Phase: at-sea, hour 14. Scheduled 4h heartbeat firing. GPS: -4.92, 119.21 (12 nm SW Pangkep). Weather currently safe. Send a short status to Pak Yusuf and a short SMS body to his wife (label SMS clearly).",
      scripted: [
        {
          delay: 200,
          text: {
            en: "4-hour heartbeat. Position -4.92, 119.21. Weather clear.",
            id: "Heartbeat 4-jam. Posisi -4.92, 119.21. Cuaca aman.",
            cn: "4 小时心跳。位置 -4.92, 119.21。天气安全。"
          }
        },
        {
          delay: 700,
          kind: "sms",
          text: {
            en: "→ Bu Yusuf: husband at 12 nm SW Pangkep · all safe · 14:00",
            id: "→ Bu Yusuf: posisi suami 12 nm SW Pangkep · semua aman · 14:00",
            cn: "→ Yusuf 夫人：丈夫位置 Pangkep 西南 12 海里 · 一切平安 · 14:00"
          }
        }
      ]
    },
    storm: {
      traceLines: [
        { tier: "cheap", msg: "trigger: bmkg.weatherChange(severity='moderate')" },
        { tier: "cheap", msg: "tool: gps.read() = -4.92, 119.21" },
        { tier: "smart", msg: "reason: storm in 6h vs 4h to nearest harbour → abort recommended" },
        { tier: "cheap", msg: "tool: sms.send(to='+62812..wife', body='aborting trip')" }
      ],
      situation:
        "Phase: at-sea, hour 14. BMKG just pushed: storm front in 6 hours, swell rising to 2.5 m. Distance to nearest harbour (Pangkep) = 4 hours at economy speed. Recommend turning back NOW. Speak to Pak Yusuf calmly but firmly, then add a one-line SMS body for his wife.",
      scripted: [
        {
          delay: 200,
          text: {
            en: "⚠ BMKG alert: storm front in 6h, swell rising to 2.5 m.",
            id: "⚠ BMKG kirim peringatan: storm front 6 jam lagi, gelombang naik ke 2.5 m.",
            cn: "⚠ BMKG 警报：6 小时后风暴锋面，浪高升至 2.5 m。"
          }
        },
        {
          delay: 800,
          text: {
            en: "Distance to nearest harbour = 4h. Recommend: turn back to Pangkep now, don't push to the spot.",
            id: "Hitung jarak ke pelabuhan terdekat = 4 jam. Saran: putar balik sekarang ke Pangkep, bukan lanjut ke spot.",
            cn: "测算到最近港口 = 4 小时。建议：立即返航 Pangkep，不要继续前往渔点。"
          }
        },
        {
          delay: 800,
          kind: "sms",
          text: {
            en: "→ Bu Yusuf: trip aborted due to weather · ETA Pangkep 18:00",
            id: "→ Bu Yusuf: trip dibatalkan karena cuaca · ETA Pangkep 18:00",
            cn: "→ Yusuf 夫人：因天气取消行程 · 预计 18:00 抵达 Pangkep"
          }
        }
      ]
    },
    catch: {
      traceLines: [
        { tier: "cheap", msg: "trigger: voiceLog.received(duration=3.2s)" },
        { tier: "cheap", msg: "tool: whisper.transcribe(lang='id') = '200 kg tongkol, area Spermonde'" },
        { tier: "cheap", msg: "tool: catchHistory.append(species='tongkol', kg=200, area='spermonde')" }
      ],
      situation:
        "Phase: at-sea, hour 14. Pak Yusuf just voice-logged (3.2s): '200 kg tongkol, area Spermonde'. Trip total now 240 kg. Confirm the entry, then mention you'll start watching TPI prices in Pangkep & Makassar to time the return.",
      scripted: [
        {
          delay: 200,
          kind: "user",
          text: {
            en: "🎙 (3 sec) '200 kg tongkol, Spermonde area'",
            id: "🎙 (3 detik) '200 kg tongkol, area Spermonde'",
            cn: "🎙 （3 秒）'200 公斤鲣鱼，Spermonde 海域'"
          }
        },
        {
          delay: 600,
          text: {
            en: "Logged. Tongkol 200 kg at Spermonde. Trip total 240 kg.",
            id: "Catat. Tongkol 200 kg di Spermonde. Total trip jadi 240 kg.",
            cn: "已记录。Spermonde 鲣鱼 200 公斤。本次行程合计 240 公斤。"
          }
        },
        {
          delay: 700,
          text: {
            en: "I'll start watching TPI prices in Pangkep & Makassar for landing timing.",
            id: "Saya mulai pantau harga TPI Pangkep & Makassar untuk timing pulang.",
            cn: "我开始监控 Pangkep 与 Makassar TPI 价格，确定返港时机。"
          }
        }
      ]
    },
    lowfuel: {
      traceLines: [
        { tier: "cheap", msg: "trigger: fuelSensor.read() = 35%" },
        { tier: "cheap", msg: "tool: fuelCalc.remainingHours(rate=8L/h) = 11h" },
        { tier: "smart", msg: "reason: 11h fuel vs 9h to dock @ economy speed → safe but tight" }
      ],
      situation:
        "Phase: at-sea. Fuel sensor: 35% (~70 L left). Burn rate at economy speed = ~8 L/h, so ~11 hours of fuel. Distance to Pangkep dock at 6 kn = ~9 hours. Tight margin — recommend heading back now rather than waiting for a full hold.",
      scripted: [
        {
          delay: 200,
          text: {
            en: "⚠ Diesel at 35% (~70 L). Good for 11h at economy speed.",
            id: "⚠ Solar tinggal 35% (~70 L). Cukup untuk 11 jam ekonomis.",
            cn: "⚠ 柴油剩 35%（约 70 升）。可经济航行 11 小时。"
          }
        },
        {
          delay: 800,
          text: {
            en: "Return to Pangkep ~9h at 6 kn. Recommend: head back now, don't wait for a full hold.",
            id: "Pulang ke Pangkep ~9 jam jika kecepatan 6 kn. Saran: pulang sekarang, jangan tunggu palka penuh.",
            cn: "返航 Pangkep 约 9 小时（6 节速度）。建议：现在返航，不要等舱满。"
          }
        }
      ]
    }
  };

  async function runSea() {
    clearScreen();
    var btn = document.getElementById("run-sea");
    btn.disabled = true;
    var event = document.getElementById("sea-event").value;
    var s = SEA_EVENTS[event];
    trace("trace-sea", s.traceLines);

    try {
      if (isLive()) {
        var reply = await callLLM(s.situation, "trace-sea");
        await renderLLMReply(reply);
      } else {
        var p = Promise.resolve();
        s.scripted.forEach(function (b) {
          p = p.then(function () {
            return step(b.delay, function () {
              bubbleMap(b.kind || "agent", b.text);
            });
          });
        });
        await p;
      }
    } catch (e) {
      bubble("agent", "⚠ live API error: " + e.message);
    } finally {
      btn.disabled = false;
    }
  }

  // ---------- post-trip scenario ----------

  function postContext() {
    var tongkol = parseInt(document.getElementById("post-tongkol").value, 10) || 0;
    var cakalang = parseInt(document.getElementById("post-cakalang").value, 10) || 0;
    var prices = {
      pangkep: { tongkol: 22000, cakalang: 28000, eta: "16:30" },
      makassar: { tongkol: 25500, cakalang: 31000, eta: "19:00" },
      barru: { tongkol: 20000, cakalang: 26000, eta: "15:00" }
    };
    function rev(p) {
      return p.tongkol * tongkol + p.cakalang * cakalang;
    }
    var pangkepRev = rev(prices.pangkep);
    var makassarRev = rev(prices.makassar);
    var barruRev = rev(prices.barru);
    var fuelCostExtra = 80000;
    var makassarNet = makassarRev - fuelCostExtra;
    var winner = makassarNet > pangkepRev && makassarNet > barruRev ? "makassar" : pangkepRev > barruRev ? "pangkep" : "barru";
    return {
      tongkol: tongkol,
      cakalang: cakalang,
      pangkepRev: pangkepRev,
      makassarRev: makassarRev,
      barruRev: barruRev,
      winner: winner
    };
  }

  function fmtRp(n) {
    return "Rp " + n.toLocaleString("id-ID");
  }

  function postTraceLines(ctx) {
    return [
      { tier: "cheap", msg: "tool: tpi.scrape(['pangkep','makassar','barru'])" },
      { tier: "cheap", msg: "tool: fuelCalc.detourCost(to='makassar') = ~Rp 80,000" },
      { tier: "smart", msg: "reason: revenue@makassar – fuel detour vs revenue@pangkep → pick " + ctx.winner },
      { tier: "cheap", msg: "tool: wa.draft(buyer='Pak Hasan', haul=...)" }
    ];
  }

  function postScripted(ctx) {
    return [
      {
        delay: 200,
        text: {
          en: "Hauls: tongkol " + ctx.tongkol + " kg, cakalang " + ctx.cakalang + " kg. Checking TPI prices nearby.",
          id: "Hasil tangkapan: tongkol " + ctx.tongkol + " kg, cakalang " + ctx.cakalang + " kg. Saya cek harga TPI sekitar.",
          cn: "渔获：鲣鱼 " + ctx.tongkol + " 公斤，鲣鱼属 " + ctx.cakalang + " 公斤。我查询周边 TPI 价格。"
        }
      },
      {
        delay: 800,
        kind: "tool",
        text: {
          en:
            "→ Pangkep: " + fmtRp(ctx.pangkepRev) + " · ETA 16:30\n→ Makassar: " + fmtRp(ctx.makassarRev) +
            " · ETA 19:00 (–Rp 80,000 fuel)\n→ Barru: " + fmtRp(ctx.barruRev) + " · ETA 15:00",
          id:
            "→ Pangkep: " + fmtRp(ctx.pangkepRev) + " · ETA 16:30\n→ Makassar: " + fmtRp(ctx.makassarRev) +
            " · ETA 19:00 (–Rp 80.000 solar)\n→ Barru: " + fmtRp(ctx.barruRev) + " · ETA 15:00",
          cn:
            "→ Pangkep：" + fmtRp(ctx.pangkepRev) + " · 预计 16:30\n→ Makassar：" + fmtRp(ctx.makassarRev) +
            " · 预计 19:00（–Rp 80,000 油费）\n→ Barru：" + fmtRp(ctx.barruRev) + " · 预计 15:00"
        }
      },
      {
        delay: 1000,
        text: {
          en: "Recommend: land at " + ctx.winner.toUpperCase() + ". Highest net after fuel and time.",
          id: "Saran: darat di " + ctx.winner.toUpperCase() + ". Net paling tinggi setelah hitung solar dan jam.",
          cn: "建议：在 " + ctx.winner.toUpperCase() + " 靠岸。扣除油费和时间后净收入最高。"
        }
      },
      {
        delay: 800,
        text: {
          en: "Drafted a WhatsApp message to Pak Hasan (" + ctx.winner.toUpperCase() + " broker). Send it?",
          id: "Saya draft pesan WA ke Pak Hasan (broker " + ctx.winner.toUpperCase() + "). Mau saya kirim?",
          cn: "我已起草发给 Hasan 先生（" + ctx.winner.toUpperCase() + " 鱼贩）的微信消息。需要发送吗？"
        }
      }
    ];
  }

  function postSituationText(ctx) {
    return [
      "Phase: post-trip dock advisor. 4 hours from shore.",
      "Hauls in hold: tongkol " + ctx.tongkol + " kg, cakalang " + ctx.cakalang + " kg.",
      "TPI auction prices fetched from 3 nearby ports:",
      "  Pangkep   gross " + fmtRp(ctx.pangkepRev) + " · ETA 16:30 (default dock)",
      "  Makassar  gross " + fmtRp(ctx.makassarRev) + " · ETA 19:00 · extra fuel ~Rp 80,000",
      "  Barru     gross " + fmtRp(ctx.barruRev) + " · ETA 15:00",
      "Net-best dock after fuel & time: " + ctx.winner.toUpperCase() + ".",
      "",
      "Tell Pak Yusuf the recommendation, give the 3 prices for context, and",
      "ask if he wants you to send the drafted WhatsApp to broker Pak Hasan."
    ].join("\n");
  }

  async function runPost() {
    clearScreen();
    var btn = document.getElementById("run-post");
    btn.disabled = true;
    var ctx = postContext();
    trace("trace-post", postTraceLines(ctx));

    try {
      if (isLive()) {
        var reply = await callLLM(postSituationText(ctx), "trace-post");
        await renderLLMReply(reply);
      } else {
        var script = postScripted(ctx);
        var p = Promise.resolve();
        script.forEach(function (s) {
          p = p.then(function () {
            return step(s.delay, function () {
              bubbleMap(s.kind || "agent", s.text);
            });
          });
        });
        await p;
      }
    } catch (e) {
      bubble("agent", "⚠ live API error: " + e.message);
    } finally {
      btn.disabled = false;
    }
  }

  // ---------- bind ----------

  document.getElementById("run-pre").addEventListener("click", runPretrip);
  document.getElementById("run-sea").addEventListener("click", runSea);
  document.getElementById("run-post").addEventListener("click", runPost);

  initProvider();

  var d = new Date();
  d.setDate(d.getDate() + 1);
  document.getElementById("pre-date").value = d.toISOString().slice(0, 10);
})();
